### ISSUE TITLE
Passive Event Listeners

### ISSUE THREAD

**Issue by benjamin-t-frost** [madebyfabian/vue-focus-visible#1]
Lighthouse is complaining of the active event listeners in this library and it doesn't appear as if active ones are necessary.

I tried to push a branch to open a PR but 403 ~

Would appreciate!

**Comment by madebyfabian** [comment]
Hi @benjamin-t-frost, thanks for your comment on this! Will look into it. Which ones are not necessary in your opinion? Since the plugin‘s functionality is only able to work when actively listening to these events.

**Comment by madebyfabian** [comment]
Ah, I see what you meant: 
<img width="781" alt="Bildschirmfoto 2021-05-21 um 10 40 52" src="https://user-images.githubusercontent.com/32813692/119108942-07a6ef80-ba21-11eb-89d5-8cd501d39c17.png">
I fixed this and released a new version (v2.2.0)
Have a nice day!
