### ISSUE TITLE
on npm.com version 2.2 is missing some files compared to previous vcer

### ISSUE THREAD

**Issue by kennethh72** [madebyfabian/vue-focus-visible#2]
https://www.npmjs.com/package/vue-focus-visible/v/2.1.0        Total 10 files
https://www.npmjs.com/package/vue-focus-visible/v/2.2.0        Total  3 Files

**Comment by madebyfabian** [comment]
Hi @kennethh72
I fixed this in v2.3.0. Have a great day :)
